// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solucoes.Infrastructure.Data;

#nullable disable

namespace Solucoes.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SolucoesDbContext))]
    partial class SolucoesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.ItemBacklogs.ItemBacklog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CriadoPorProjetoMembroId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemBacklogStatusId")
                        .HasColumnType("int");

                    b.Property<int>("ItemBacklogTipoId")
                        .HasColumnType("int");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("int");

                    b.Property<int?>("ResponsavelProjetoMembroId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorProjetoMembroId");

                    b.HasIndex("ItemBacklogStatusId");

                    b.HasIndex("ItemBacklogTipoId");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("ResponsavelProjetoMembroId");

                    b.ToTable("ItemBacklogs", (string)null);
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.ItemBacklogs.ItemBacklogAnexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CriadoPorProjetoMembroId")
                        .HasColumnType("int");

                    b.Property<int>("ItemBacklogId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorProjetoMembroId");

                    b.HasIndex("ItemBacklogId");

                    b.ToTable("ItemBacklogAnexos", (string)null);
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.ItemBacklogs.ItemBacklogComentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CriadoPorProjetoMembroId")
                        .HasColumnType("int");

                    b.Property<int>("ItemBacklogId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorProjetoMembroId");

                    b.HasIndex("ItemBacklogId");

                    b.ToTable("ItemBacklogComentarios", (string)null);
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.ItemBacklogs.ItemBacklogHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AlteradoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("AlteradoPorProjetoMembroId")
                        .HasColumnType("int");

                    b.Property<int>("ItemBacklogId")
                        .HasColumnType("int");

                    b.Property<int>("ItemBacklogStatusAnteriorId")
                        .HasColumnType("int");

                    b.Property<int>("ItemBacklogStatusAtualId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlteradoPorProjetoMembroId");

                    b.HasIndex("ItemBacklogId");

                    b.HasIndex("ItemBacklogStatusAnteriorId");

                    b.HasIndex("ItemBacklogStatusAtualId");

                    b.ToTable("ItemBacklogHistoricos", (string)null);
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.ItemBacklogs.ItemBacklogStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ItemBacklogStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "BACKLOG",
                            Nome = "Backlog"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "EM_ANDAMENTO",
                            Nome = "Em Andamento"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "EM_REVISAO",
                            Nome = "Em revisão"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "CONCLUIDO",
                            Nome = "Concluído"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "CANCELADO",
                            Nome = "Cancelado"
                        });
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.ItemBacklogs.ItemBacklogTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ItemBacklogTipos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "HISTORIA_USUARIO",
                            Nome = "História de Usuário"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "TAREFA",
                            Nome = "Tarefa"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "BUG",
                            Nome = "Bug"
                        });
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CriadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.ToTable("Projetos", (string)null);
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.ProjetoConvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aceito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CriadoPorProjetoMembroId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("int");

                    b.Property<int>("ProjetoPapelId")
                        .HasColumnType("int");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varbinary(32)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorProjetoMembroId");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("ProjetoPapelId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("ProjetoConvites", (string)null);
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.ProjetoMembro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.Property<DateTime>("EntrouEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("int");

                    b.Property<int>("ProjetoPapelId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("ProjetoPapelId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ProjetoMembros", (string)null);
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.ProjetoPapel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ProjetoPapeis", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "PRODUCT_OWNER",
                            Nome = "Product Owner"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "SCRUM_MASTER",
                            Nome = "Scrum Master"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "DESENVOLVEDOR",
                            Nome = "Desenvolvedor"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "STAKEHOLDER",
                            Nome = "Stakeholder"
                        });
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.Sprints.Sprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CriadoPorProjetoMembroId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Encerrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorProjetoMembroId");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Sprints", (string)null);
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.Sprints.SprintBacklog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemBacklogId")
                        .HasColumnType("int");

                    b.Property<int>("SprintId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemBacklogId");

                    b.HasIndex("SprintId");

                    b.ToTable("SprintBacklogs", (string)null);
                });

            modelBuilder.Entity("Solucoes.Infrastructure.Data.Identity.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PrimeiroNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Solucoes.Infrastructure.Data.Identity.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Solucoes.Infrastructure.Data.Identity.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Solucoes.Infrastructure.Data.Identity.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Solucoes.Infrastructure.Data.Identity.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.ItemBacklogs.ItemBacklog", b =>
                {
                    b.HasOne("Solucoes.Domain.Entities.Projetos.ProjetoMembro", "CriadoPorProjetoMembro")
                        .WithMany()
                        .HasForeignKey("CriadoPorProjetoMembroId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Solucoes.Domain.Entities.Projetos.ItemBacklogs.ItemBacklogStatus", "ItemBacklogStatus")
                        .WithMany()
                        .HasForeignKey("ItemBacklogStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Solucoes.Domain.Entities.Projetos.ItemBacklogs.ItemBacklogTipo", "ItemBacklogTipo")
                        .WithMany()
                        .HasForeignKey("ItemBacklogTipoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Solucoes.Domain.Entities.Projetos.Projeto", "Projeto")
                        .WithMany("Backlog")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Solucoes.Domain.Entities.Projetos.ProjetoMembro", "ResponsavelProjetoMembro")
                        .WithMany("Tarefas")
                        .HasForeignKey("ResponsavelProjetoMembroId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CriadoPorProjetoMembro");

                    b.Navigation("ItemBacklogStatus");

                    b.Navigation("ItemBacklogTipo");

                    b.Navigation("Projeto");

                    b.Navigation("ResponsavelProjetoMembro");
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.ItemBacklogs.ItemBacklogAnexo", b =>
                {
                    b.HasOne("Solucoes.Domain.Entities.Projetos.ProjetoMembro", "CriadoPorProjetoMembro")
                        .WithMany()
                        .HasForeignKey("CriadoPorProjetoMembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Solucoes.Domain.Entities.Projetos.ItemBacklogs.ItemBacklog", "ItemBacklog")
                        .WithMany("Anexos")
                        .HasForeignKey("ItemBacklogId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CriadoPorProjetoMembro");

                    b.Navigation("ItemBacklog");
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.ItemBacklogs.ItemBacklogComentario", b =>
                {
                    b.HasOne("Solucoes.Domain.Entities.Projetos.ProjetoMembro", "CriadoPorProjetoMembro")
                        .WithMany()
                        .HasForeignKey("CriadoPorProjetoMembroId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Solucoes.Domain.Entities.Projetos.ItemBacklogs.ItemBacklog", "ItemBacklog")
                        .WithMany("Comentarios")
                        .HasForeignKey("ItemBacklogId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CriadoPorProjetoMembro");

                    b.Navigation("ItemBacklog");
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.ItemBacklogs.ItemBacklogHistorico", b =>
                {
                    b.HasOne("Solucoes.Domain.Entities.Projetos.ProjetoMembro", "AlteradoPorProjetoMembro")
                        .WithMany()
                        .HasForeignKey("AlteradoPorProjetoMembroId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Solucoes.Domain.Entities.Projetos.ItemBacklogs.ItemBacklog", "ItemBacklog")
                        .WithMany("Historico")
                        .HasForeignKey("ItemBacklogId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Solucoes.Domain.Entities.Projetos.ItemBacklogs.ItemBacklogStatus", "ItemBacklogStatusAnterior")
                        .WithMany()
                        .HasForeignKey("ItemBacklogStatusAnteriorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Solucoes.Domain.Entities.Projetos.ItemBacklogs.ItemBacklogStatus", "ItemBacklogStatusAtual")
                        .WithMany()
                        .HasForeignKey("ItemBacklogStatusAtualId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AlteradoPorProjetoMembro");

                    b.Navigation("ItemBacklog");

                    b.Navigation("ItemBacklogStatusAnterior");

                    b.Navigation("ItemBacklogStatusAtual");
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.Projeto", b =>
                {
                    b.HasOne("Solucoes.Infrastructure.Data.Identity.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.ProjetoConvite", b =>
                {
                    b.HasOne("Solucoes.Domain.Entities.Projetos.ProjetoMembro", "CriadoPorProjetoMembro")
                        .WithMany("ProjetoConvites")
                        .HasForeignKey("CriadoPorProjetoMembroId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Solucoes.Domain.Entities.Projetos.Projeto", "Projeto")
                        .WithMany("Convites")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Solucoes.Domain.Entities.Projetos.ProjetoPapel", "ProjetoPapel")
                        .WithMany()
                        .HasForeignKey("ProjetoPapelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Solucoes.Infrastructure.Data.Identity.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CriadoPorProjetoMembro");

                    b.Navigation("Projeto");

                    b.Navigation("ProjetoPapel");
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.ProjetoMembro", b =>
                {
                    b.HasOne("Solucoes.Domain.Entities.Projetos.Projeto", "Projeto")
                        .WithMany("Membros")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Solucoes.Domain.Entities.Projetos.ProjetoPapel", "ProjetoPapel")
                        .WithMany()
                        .HasForeignKey("ProjetoPapelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Solucoes.Infrastructure.Data.Identity.Entities.Usuario", null)
                        .WithMany("Projetos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Projeto");

                    b.Navigation("ProjetoPapel");
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.Sprints.Sprint", b =>
                {
                    b.HasOne("Solucoes.Domain.Entities.Projetos.ProjetoMembro", "CriadoPorProjetoMembro")
                        .WithMany()
                        .HasForeignKey("CriadoPorProjetoMembroId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Solucoes.Domain.Entities.Projetos.Projeto", "Projeto")
                        .WithMany("Sprints")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CriadoPorProjetoMembro");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.Sprints.SprintBacklog", b =>
                {
                    b.HasOne("Solucoes.Domain.Entities.Projetos.ItemBacklogs.ItemBacklog", "ItemBacklog")
                        .WithMany("Sprints")
                        .HasForeignKey("ItemBacklogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Solucoes.Domain.Entities.Projetos.Sprints.Sprint", "Sprint")
                        .WithMany("Backlog")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ItemBacklog");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.ItemBacklogs.ItemBacklog", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Comentarios");

                    b.Navigation("Historico");

                    b.Navigation("Sprints");
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.Projeto", b =>
                {
                    b.Navigation("Backlog");

                    b.Navigation("Convites");

                    b.Navigation("Membros");

                    b.Navigation("Sprints");
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.ProjetoMembro", b =>
                {
                    b.Navigation("ProjetoConvites");

                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("Solucoes.Domain.Entities.Projetos.Sprints.Sprint", b =>
                {
                    b.Navigation("Backlog");
                });

            modelBuilder.Entity("Solucoes.Infrastructure.Data.Identity.Entities.Usuario", b =>
                {
                    b.Navigation("Projetos");
                });
#pragma warning restore 612, 618
        }
    }
}
